apiVersion: v1
kind: Service
metadata:
  name: awesome-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: awesome-app
    app.kubernetes.io/instance: {{ .Release.Name }}
